CREATE TABLE admin_users (
 id text PRIMARY KEY, username text NOT NULL UNIQUE CHECK(username=lower(username)), display_name text NOT NULL,
 password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('superadmin','admin')),
 enabled integer NOT NULL DEFAULT 1 CHECK(enabled IN(0,1)), created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX one_superadmin ON admin_users(role) WHERE role='superadmin';
CREATE TABLE admin_sessions(token_hash text PRIMARY KEY,user_id text NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,expires_at bigint NOT NULL);
CREATE INDEX admin_sessions_user ON admin_sessions(user_id);
CREATE INDEX admin_sessions_expiry ON admin_sessions(expires_at);
CREATE TABLE admin_login_attempts(username text PRIMARY KEY,count integer NOT NULL,reset_at bigint NOT NULL);
CREATE TABLE pathogens(code text PRIMARY KEY,name text NOT NULL);
CREATE TABLE imports (
 id text PRIMARY KEY,file_name text NOT NULL,sha256 text NOT NULL,
 province_code text NOT NULL,province text NOT NULL,city_code text NOT NULL,city text NOT NULL,county_code text NOT NULL DEFAULT '',county text NOT NULL DEFAULT '',
 submitted_by text,submitted_name text NOT NULL,submitted_username text NOT NULL DEFAULT '',report_date date NOT NULL,created_at timestamptz NOT NULL,
 status text NOT NULL CHECK(status IN('staged','published','withdrawn','expired','cancelled')),
 source_sheet text NOT NULL DEFAULT 'Sheet1',warnings jsonb NOT NULL DEFAULT '[]',payload jsonb,summary jsonb NOT NULL DEFAULT '{}',
 withdrawn_at timestamptz,withdrawn_by text,withdrawn_name text,demo integer NOT NULL DEFAULT 0 CHECK(demo IN(0,1)),expires_at timestamptz
);
CREATE INDEX imports_owner ON imports(submitted_by,created_at DESC,id);
CREATE INDEX imports_filter ON imports(demo,report_date,province_code,city_code,county_code) WHERE status='published';
CREATE INDEX imports_expiry ON imports(expires_at) WHERE status='staged';
CREATE TABLE samples(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,import_id text NOT NULL REFERENCES imports(id),batch text NOT NULL,sample_code text NOT NULL,UNIQUE(import_id,batch,sample_code));
CREATE TABLE results(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sample_id bigint NOT NULL REFERENCES samples(id),pathogen_code text NOT NULL REFERENCES pathogens(code),status text NOT NULL CHECK(status IN('positive','negative')),ct double precision,raw_value text NOT NULL,raw_name text NOT NULL,source_row integer NOT NULL,UNIQUE(sample_id,pathogen_code));
CREATE TABLE import_metrics(import_id text NOT NULL REFERENCES imports(id),pathogen_code text NOT NULL,tested bigint NOT NULL CHECK(tested>=0),positive bigint NOT NULL CHECK(positive>=0 AND positive<=tested),PRIMARY KEY(import_id,pathogen_code));
CREATE INDEX metrics_pathogen ON import_metrics(pathogen_code,import_id);
CREATE TABLE dataset_state(id integer PRIMARY KEY CHECK(id=1),revision bigint NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now(),maintenance boolean NOT NULL DEFAULT false);
INSERT INTO dataset_state(id) VALUES(1);
CREATE TABLE jobs (
 id text PRIMARY KEY,import_id text NOT NULL UNIQUE REFERENCES imports(id),owner_id text NOT NULL,
 phase text NOT NULL DEFAULT 'parse' CHECK(phase IN('parse','commit')),
 status text NOT NULL CHECK(status IN('queued','running','ready','succeeded','failed','cancelled','expired')),
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),attempts integer NOT NULL DEFAULT 0,
 lease_token text,lease_until timestamptz,next_attempt_at timestamptz NOT NULL DEFAULT now(),error text,error_code text,retryable boolean NOT NULL DEFAULT false
);
CREATE INDEX jobs_claim ON jobs(status,next_attempt_at,created_at) WHERE status IN('queued','running');
CREATE INDEX jobs_owner ON jobs(owner_id,created_at DESC,id);
CREATE TABLE job_attempts(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,job_id text NOT NULL REFERENCES jobs(id),phase text NOT NULL,attempt integer NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz,outcome text,error_code text);
CREATE TABLE worker_heartbeats(id text PRIMARY KEY,seen_at timestamptz NOT NULL DEFAULT now());
